name: Democracy Enforcer
description: Enforce democracy on a repository by merging pull requests by voting score.
author: deuzu

branding:
  icon: alert-octagon
  color: green

inputs:
  githubToken:
    required: true
    description: The Github token that give permission on the repository.
  dryRun:
    required: false
    description: "When `dryRun: true` the Github democrat won't merge any pull requests"
    default: false
  prMinimumReviewScore:
    required: false
    description: The minimum pull request review score needed to be eligible for merge (approves +1, request changes -1)
    default: 1
  prVotingTimeHours:
    required: false
    description: The delay (in hours and since the last commit) needed before a pull request is eligible for merge
    default: 24
  prMarkAsMegeableLabel:
    required: false
    description: The pull request label needed to be eligible for merge
    default: ready
  prTargetBranch:
    required: false
    description: The pull request target branch
    default: main
runs:
  using: node12
  main: dist/index.js
